-- ============================================================
-- Database Schema: My Thai Star Restaurant Management System
-- Dialect:         PostgreSQL 14+
-- Generated from:  JPA Entity Analysis + Flyway Migration Scripts
-- Source files:    java/mtsj/core/src/main/resources/db/specific/h2/
--                  java/mtsj/core/src/main/java/.../dataaccess/api/
--                  net/database/SQLServer/Scripts/
-- Date:            2025-01-01
-- ============================================================
--
-- DOMAIN OVERVIEW
-- ───────────────
-- User Management  : user_role, "user", user_favourite
-- Dish Management  : category, image, dish, dish_category,
--                    ingredient, dish_ingredient
-- Booking Mgmt     : restaurant_table, booking, invited_guest
-- Order Mgmt       : orders, order_line, order_dish_extra_ingredient
-- Analytics/ML     : date_info, prediction_all_forecast,
--                    prediction_all_models, prediction_forecast_data
-- Clustering       : addresses
-- Infrastructure   : binary_object, rev_info
--
-- BUSINESS RULES (encoded as constraints)
-- ────────────────────────────────────────
-- BR-001  Token format CB_YYYYMMDD_<MD5> for host bookings
-- BR-002  Token format GB_YYYYMMDD_<MD5> for guest bookings
-- BR-003  expirationDate = bookingDate − 1 hour (application layer)
-- BR-004  assistants ∈ [1, 99]  (@Min=1, @Digits integer=2)
-- BR-005  Booking.canceled defaults to FALSE
-- BR-006  User.twoFactorStatus defaults to FALSE
-- BR-007  Dish price ≥ 0, Ingredient price ≥ 0
-- BR-008  OrderLine.amount ≥ 1
-- BR-009  username UNIQUE + NOT NULL; email NOT NULL
-- BR-010  Dish has exactly one Image (OneToOne, UNIQUE FK)
-- BR-011  Cancellation window: before bookingDate − hoursLimit hours
--         (application-configured: mythaistar.hourslimitcancellation)
-- BR-012  modificationCounter supports optimistic-locking (JPA @Version)
-- ============================================================

-- ============================================================
-- IDENTITY STRATEGY NOTE
-- ============================================================
-- Using PostgreSQL GENERATED BY DEFAULT AS IDENTITY (SQL:2003)
-- Started at 1 000 000 to match Hibernate's global HIBERNATE_SEQUENCE
-- used in H2 / SAP HANA profiles, preserving ID-space parity for
-- any cross-profile data migration.

-- ============================================================
-- TABLE: user_role
-- Description: Role definitions – Customer (0), Waiter (1), Manager (2)
-- Domain: User Management
-- ============================================================
CREATE TABLE user_role (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    name                 VARCHAR(255),
    active               BOOLEAN  NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_user_role       PRIMARY KEY (id),
    CONSTRAINT uq_user_role_name  UNIQUE (name),
    CONSTRAINT chk_user_role_name CHECK (name IN ('Customer', 'Waiter', 'Manager'))
);

COMMENT ON TABLE  user_role              IS 'Application roles assigned to users. Seed values: Customer(0), Waiter(1), Manager(2)';
COMMENT ON COLUMN user_role.id           IS 'Surrogate primary key';
COMMENT ON COLUMN user_role.modification_counter IS 'Optimistic-locking version counter (JPA @Version equivalent, BR-012)';
COMMENT ON COLUMN user_role.name         IS 'Role display name: Customer | Waiter | Manager';
COMMENT ON COLUMN user_role.active       IS 'Soft-disable a role without deleting it (defaults TRUE)';

-- ============================================================
-- TABLE: image
-- Description: Binary dish images stored as BYTEA BLOBs
-- Domain: Dish Management
-- ============================================================
CREATE TABLE image (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    name                 VARCHAR(255),
    content              BYTEA,
    content_type         INTEGER,
    mime_type            VARCHAR(255),

    CONSTRAINT pk_image PRIMARY KEY (id)
);

COMMENT ON TABLE  image              IS 'Raw image data (JPEG/PNG) attached to Dish records; stored as BYTEA';
COMMENT ON COLUMN image.content      IS 'Raw binary image payload';
COMMENT ON COLUMN image.content_type IS 'Enum ordinal for image content type (0=JPEG, 1=PNG, etc.)';
COMMENT ON COLUMN image.mime_type    IS 'IANA MIME type string, e.g. image/jpeg, image/png';

CREATE INDEX idx_image_mime_type ON image(mime_type);

-- ============================================================
-- TABLE: category
-- Description: Dish taxonomy tags (Thai, Vegetarian, Vegan, ...)
-- Domain: Dish Management
-- ============================================================
CREATE TABLE category (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    name                 VARCHAR(255),
    description          VARCHAR(4000),
    show_order           INTEGER  DEFAULT 0,

    CONSTRAINT pk_category PRIMARY KEY (id)
);

COMMENT ON TABLE  category            IS 'Dish categories used for menu filtering; e.g. Thai, Vegetarian, Vegan, Curry, etc.';
COMMENT ON COLUMN category.show_order IS 'UI display sort order (ascending)';

CREATE INDEX idx_category_name       ON category(name);
CREATE INDEX idx_category_show_order ON category(show_order);

-- ============================================================
-- TABLE: ingredient
-- Description: Selectable extra ingredients / toppings
-- Domain: Dish Management
-- ============================================================
CREATE TABLE ingredient (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    name                 VARCHAR(255),
    description          VARCHAR(4000),
    price                DECIMAL(16, 10),

    CONSTRAINT pk_ingredient        PRIMARY KEY (id),
    CONSTRAINT chk_ingredient_price CHECK (price IS NULL OR price >= 0)  -- BR-007
);

COMMENT ON TABLE  ingredient       IS 'Optional extra ingredients selectable per OrderLine (e.g. extra basil, extra chilli)';
COMMENT ON COLUMN ingredient.price IS 'Additional surcharge for this extra; 0.00 = free add-on (BR-007: must be ≥ 0)';

CREATE INDEX idx_ingredient_name ON ingredient(name);

-- ============================================================
-- TABLE: "user"
-- Description: Application user accounts with BCrypt-hashed passwords
-- Domain: User Management
-- NOTE: "user" is a reserved word in PostgreSQL – quoted throughout.
-- ============================================================
CREATE TABLE "user" (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    username             VARCHAR(255) NOT NULL,
    password             VARCHAR(255) NOT NULL,
    secret               VARCHAR(255),
    two_factor_status    BOOLEAN  NOT NULL DEFAULT FALSE,
    email                VARCHAR(120) NOT NULL,
    id_role              BIGINT   NOT NULL,

    CONSTRAINT pk_user          PRIMARY KEY (id),
    CONSTRAINT uq_user_username UNIQUE (username),           -- BR-009
    CONSTRAINT uq_user_email    UNIQUE (email),              -- BR-009
    CONSTRAINT fk_user_role     FOREIGN KEY (id_role)
                                    REFERENCES user_role (id)
                                    ON DELETE RESTRICT
                                    ON UPDATE CASCADE
);

COMMENT ON TABLE  "user"                  IS 'Application user accounts. Passwords stored as Spring Security bcrypt hashes: {bcrypt}$2a$10$...';
COMMENT ON COLUMN "user".username         IS 'Login username – unique, case-sensitive (BR-009)';
COMMENT ON COLUMN "user".password         IS 'BCrypt-hashed password with {bcrypt} prefix for DelegatingPasswordEncoder';
COMMENT ON COLUMN "user".secret           IS 'Base32-encoded TOTP secret for two-factor authentication';
COMMENT ON COLUMN "user".two_factor_status IS 'TRUE when TOTP 2FA is enabled; defaults FALSE (BR-006)';
COMMENT ON COLUMN "user".email            IS 'Contact email; unique constraint (BR-009); max 120 chars';
COMMENT ON COLUMN "user".id_role          IS 'FK → user_role(id)';

CREATE INDEX idx_user_username ON "user"(username);
CREATE INDEX idx_user_email    ON "user"(email);
CREATE INDEX idx_user_id_role  ON "user"(id_role);

-- ============================================================
-- TABLE: dish
-- Description: Menu items with prices (BigDecimal for precision)
-- Domain: Dish Management
-- ============================================================
CREATE TABLE dish (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    name                 VARCHAR(255),
    description          VARCHAR(4000),
    price                DECIMAL(16, 10),
    id_image             BIGINT   NOT NULL,

    CONSTRAINT pk_dish        PRIMARY KEY (id),
    CONSTRAINT uq_dish_image  UNIQUE (id_image),         -- BR-010: OneToOne – one image per dish
    CONSTRAINT fk_dish_image  FOREIGN KEY (id_image)
                                  REFERENCES image (id)
                                  ON DELETE RESTRICT,
    CONSTRAINT chk_dish_price CHECK (price IS NULL OR price >= 0)  -- BR-007
);

COMMENT ON TABLE  dish          IS 'A menu dish in the My Thai Star restaurant catalogue';
COMMENT ON COLUMN dish.price    IS 'Base price; DECIMAL(16,10) for high monetary precision (BR-007: price ≥ 0)';
COMMENT ON COLUMN dish.id_image IS 'FK → image(id); UNIQUE enforces OneToOne relationship (BR-010)';

CREATE INDEX idx_dish_name     ON dish(name);
CREATE INDEX idx_dish_id_image ON dish(id_image);

-- ============================================================
-- TABLE: dish_category  [Junction: Dish ↔ Category M:N]
-- ============================================================
CREATE TABLE dish_category (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER NOT NULL DEFAULT 0,
    id_dish              BIGINT  NOT NULL,
    id_category          BIGINT  NOT NULL,

    CONSTRAINT pk_dish_category      PRIMARY KEY (id),
    CONSTRAINT uq_dish_category      UNIQUE (id_dish, id_category),
    CONSTRAINT fk_dish_category_dish FOREIGN KEY (id_dish)
                                         REFERENCES dish (id)
                                         ON DELETE CASCADE,
    CONSTRAINT fk_dish_category_cat  FOREIGN KEY (id_category)
                                         REFERENCES category (id)
                                         ON DELETE CASCADE
);

COMMENT ON TABLE dish_category IS 'Many-to-many: a dish can belong to multiple categories (e.g. Thai + Curry + Main)';

CREATE INDEX idx_dish_category_dish ON dish_category(id_dish);
CREATE INDEX idx_dish_category_cat  ON dish_category(id_category);

-- ============================================================
-- TABLE: dish_ingredient  [Junction: Dish ↔ Ingredient M:N]
-- Description: Which extra ingredients are available per dish
-- ============================================================
CREATE TABLE dish_ingredient (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER NOT NULL DEFAULT 0,
    id_dish              BIGINT  NOT NULL,
    id_ingredient        BIGINT  NOT NULL,

    CONSTRAINT pk_dish_ingredient          PRIMARY KEY (id),
    CONSTRAINT uq_dish_ingredient          UNIQUE (id_dish, id_ingredient),
    CONSTRAINT fk_dish_ingredient_dish     FOREIGN KEY (id_dish)
                                               REFERENCES dish (id)
                                               ON DELETE CASCADE,
    CONSTRAINT fk_dish_ingredient_ingr     FOREIGN KEY (id_ingredient)
                                               REFERENCES ingredient (id)
                                               ON DELETE CASCADE
);

COMMENT ON TABLE dish_ingredient IS 'Many-to-many: defines which extra ingredients can be added to each dish';

CREATE INDEX idx_dish_ingredient_dish ON dish_ingredient(id_dish);
CREATE INDEX idx_dish_ingredient_ingr ON dish_ingredient(id_ingredient);

-- ============================================================
-- TABLE: user_favourite  [Junction: User ↔ Dish M:N]
-- Description: User's bookmarked favourite dishes
-- ============================================================
CREATE TABLE user_favourite (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER NOT NULL DEFAULT 0,
    id_user              BIGINT  NOT NULL,
    id_dish              BIGINT  NOT NULL,

    CONSTRAINT pk_user_favourite         PRIMARY KEY (id),
    CONSTRAINT uq_user_favourite         UNIQUE (id_user, id_dish),
    CONSTRAINT fk_user_favourite_user    FOREIGN KEY (id_user)
                                             REFERENCES "user" (id)
                                             ON DELETE CASCADE,
    CONSTRAINT fk_user_favourite_dish    FOREIGN KEY (id_dish)
                                             REFERENCES dish (id)
                                             ON DELETE CASCADE
);

COMMENT ON TABLE user_favourite IS 'User wish-list / favourites: many-to-many between User and Dish; JPA @ManyToMany via @JoinTable';

CREATE INDEX idx_user_favourite_user ON user_favourite(id_user);
CREATE INDEX idx_user_favourite_dish ON user_favourite(id_dish);

-- ============================================================
-- TABLE: restaurant_table
-- Description: Physical restaurant tables with seating capacity
-- Domain: Booking Management
-- NOTE: Original name "Table" is a SQL reserved word; renamed to
--       restaurant_table. JPA entity still maps to original "Table".
-- ============================================================
CREATE TABLE restaurant_table (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER NOT NULL DEFAULT 0,
    seats_number         INTEGER NOT NULL,

    CONSTRAINT pk_restaurant_table      PRIMARY KEY (id),
    CONSTRAINT chk_table_seats_positive CHECK (seats_number > 0)
);

COMMENT ON TABLE  restaurant_table             IS 'Physical restaurant tables. Original H2/HANA name: "Table". Seating: 4, 6, or 8 per seed data';
COMMENT ON COLUMN restaurant_table.seats_number IS 'Max capacity; party size must be ≤ this value (validated at application layer)';

-- ============================================================
-- TABLE: booking
-- Description: Table reservations (host + group bookings)
-- Domain: Booking Management
--
-- CIRCULAR REFERENCE RESOLUTION:
--   booking.id_order → orders(id)   [host's order for this booking]
--   orders.id_booking → booking(id)  [the booking an order belongs to]
-- Strategy: Create booking without the id_order FK first,
--           then add it as a DEFERRABLE FK after orders is created.
-- ============================================================
CREATE TABLE booking (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER      NOT NULL DEFAULT 0,
    id_user              BIGINT,
    name                 VARCHAR(255) NOT NULL,
    booking_token        VARCHAR(60),
    comment              VARCHAR(4000),
    email                VARCHAR(255) NOT NULL,
    booking_date         TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date      TIMESTAMP WITH TIME ZONE,
    creation_date        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    canceled             BOOLEAN      NOT NULL DEFAULT FALSE,
    booking_type         INTEGER,
    id_table             BIGINT,
    id_order             BIGINT,   -- Resolved FK added below via ALTER TABLE
    assistants           INTEGER,

    CONSTRAINT pk_booking        PRIMARY KEY (id),
    CONSTRAINT uq_booking_token  UNIQUE (booking_token),
    CONSTRAINT fk_booking_user   FOREIGN KEY (id_user)
                                     REFERENCES "user" (id)
                                     ON DELETE SET NULL,
    CONSTRAINT fk_booking_table  FOREIGN KEY (id_table)
                                     REFERENCES restaurant_table (id)
                                     ON DELETE SET NULL,

    -- BR-004: assistants must be between 1 and 99 (@Min=1, @Digits(integer=2))
    CONSTRAINT chk_booking_assistants CHECK (
        assistants IS NULL OR (assistants >= 1 AND assistants <= 99)
    ),

    -- BR-001 / BR-002: token format validation
    --   Host  tokens: CB_YYYYMMDD_<32-char md5hex>
    --   Guest tokens: GB_YYYYMMDD_<32-char md5hex>
    CONSTRAINT chk_booking_token_format CHECK (
        booking_token IS NULL OR
        booking_token ~ '^(CB|GB)_[0-9]{8}_[0-9a-f]{32}$'
    ),

    -- BR-003: expiration must be before booking date (= bookingDate - 1 hour)
    CONSTRAINT chk_booking_expiration CHECK (
        expiration_date IS NULL OR expiration_date < booking_date
    ),

    -- booking_type: 0 = CommonBooking (CSR), 1 = GuestInviteBooking (GSR)
    CONSTRAINT chk_booking_type CHECK (booking_type IN (0, 1))
);

COMMENT ON TABLE  booking               IS 'Table reservation. booking_type=0: single-party; booking_type=1: group invite with InvitedGuest records';
COMMENT ON COLUMN booking.booking_token IS 'Unique access token (BR-001: CB_YYYYMMDD_<md5> for host). Immutable after creation';
COMMENT ON COLUMN booking.booking_date  IS 'UTC timestamp of the reserved slot (stored as Instant / TIMESTAMP WITH TIME ZONE)';
COMMENT ON COLUMN booking.expiration_date IS 'Auto-computed = booking_date − 1 hour (BR-003); guest must accept before this deadline';
COMMENT ON COLUMN booking.creation_date IS 'Server timestamp when the booking was persisted';
COMMENT ON COLUMN booking.canceled      IS 'Soft-cancel; TRUE after cancellation (BR-005 default: FALSE). BR-011: must cancel before bookingDate − hoursLimit';
COMMENT ON COLUMN booking.booking_type  IS '0=CommonBooking (CSR), 1=GuestSharingBooking (GSR)';
COMMENT ON COLUMN booking.id_order      IS 'FK → orders(id): the host order for this booking. Deferred FK added post-table-creation';
COMMENT ON COLUMN booking.assistants    IS 'Party size incl. host; range 1–99 (BR-004). NULL for guest-invite bookings';

CREATE INDEX idx_booking_token     ON booking(booking_token);
CREATE INDEX idx_booking_id_user   ON booking(id_user);
CREATE INDEX idx_booking_id_table  ON booking(id_table);
CREATE INDEX idx_booking_date      ON booking(booking_date);
CREATE INDEX idx_booking_canceled  ON booking(canceled);
CREATE INDEX idx_booking_type      ON booking(booking_type);
CREATE INDEX idx_booking_email     ON booking(email);
-- Composite: active bookings per user by date (common API query pattern)
CREATE INDEX idx_booking_user_date ON booking(id_user, booking_date) WHERE canceled = FALSE;

-- ============================================================
-- TABLE: invited_guest
-- Description: Guests invited to group bookings (booking_type=1)
-- Domain: Booking Management
-- ============================================================
CREATE TABLE invited_guest (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    id_booking           BIGINT   NOT NULL,
    guest_token          VARCHAR(60),
    email                VARCHAR(60),
    accepted             BOOLEAN  DEFAULT FALSE,
    modification_date    TIMESTAMP WITH TIME ZONE,
    id_order             BIGINT,  -- FK added post-orders creation

    CONSTRAINT pk_invited_guest          PRIMARY KEY (id),
    CONSTRAINT uq_invited_guest_token    UNIQUE (guest_token),
    CONSTRAINT fk_invited_guest_booking  FOREIGN KEY (id_booking)
                                             REFERENCES booking (id)
                                             ON DELETE CASCADE,

    -- BR-002: guest token format GB_YYYYMMDD_<md5>
    CONSTRAINT chk_guest_token_format CHECK (
        guest_token IS NULL OR
        guest_token ~ '^GB_[0-9]{8}_[0-9a-f]{32}$'
    )
);

COMMENT ON TABLE  invited_guest                IS 'Email-invited guest linked to a group booking (booking.booking_type=1)';
COMMENT ON COLUMN invited_guest.guest_token    IS 'Unique guest access token (BR-002). Format: GB_YYYYMMDD_<md5hex>. Set on save, immutable';
COMMENT ON COLUMN invited_guest.accepted       IS 'TRUE when guest clicked their email confirmation link; defaults FALSE';
COMMENT ON COLUMN invited_guest.modification_date IS 'Timestamp of last acceptance-status change';
COMMENT ON COLUMN invited_guest.id_order       IS 'FK → orders(id): the guest order placed for this invitation. Deferred FK';

CREATE INDEX idx_invited_guest_booking  ON invited_guest(id_booking);
CREATE INDEX idx_invited_guest_token    ON invited_guest(guest_token);
CREATE INDEX idx_invited_guest_email    ON invited_guest(email);
CREATE INDEX idx_invited_guest_accepted ON invited_guest(accepted);

-- ============================================================
-- TABLE: orders
-- Description: Customer orders linked to bookings and/or guests
-- Domain: Order Management
-- ============================================================
CREATE TABLE orders (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    id_booking           BIGINT   NOT NULL,
    id_invited_guest     BIGINT,  -- NULL for host orders
    id_host              BIGINT,  -- FK → booking(id): host booking for guest-linked orders

    CONSTRAINT pk_orders               PRIMARY KEY (id),
    CONSTRAINT fk_orders_booking       FOREIGN KEY (id_booking)
                                           REFERENCES booking (id)
                                           ON DELETE CASCADE,
    CONSTRAINT fk_orders_invited_guest FOREIGN KEY (id_invited_guest)
                                           REFERENCES invited_guest (id)
                                           ON DELETE SET NULL,
    CONSTRAINT fk_orders_host          FOREIGN KEY (id_host)
                                           REFERENCES booking (id)
                                           ON DELETE SET NULL
);

COMMENT ON TABLE  orders                IS 'An order placed for a booking. Host orders: id_invited_guest=NULL, id_host=NULL. Guest orders: id_invited_guest IS NOT NULL';
COMMENT ON COLUMN orders.id_booking     IS 'FK → booking(id): the booking context for this order (CASCADE delete)';
COMMENT ON COLUMN orders.id_invited_guest IS 'FK → invited_guest(id): set only for orders placed by an invited guest; NULL for host';
COMMENT ON COLUMN orders.id_host        IS 'FK → booking(id): for guest orders, references the host booking. NULL for host orders';

CREATE INDEX idx_orders_booking        ON orders(id_booking);
CREATE INDEX idx_orders_invited_guest  ON orders(id_invited_guest);
CREATE INDEX idx_orders_host           ON orders(id_host);

-- ============================================================
-- RESOLVE CIRCULAR FOREIGN KEYS (deferred)
-- ============================================================
-- booking.id_order → orders(id)
ALTER TABLE booking
    ADD CONSTRAINT fk_booking_order
        FOREIGN KEY (id_order)
        REFERENCES orders (id)
        ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED;

-- invited_guest.id_order → orders(id)
ALTER TABLE invited_guest
    ADD CONSTRAINT fk_invited_guest_order
        FOREIGN KEY (id_order)
        REFERENCES orders (id)
        ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED;

-- ============================================================
-- TABLE: order_line
-- Description: Individual dish items within an order
-- Domain: Order Management
-- ============================================================
CREATE TABLE order_line (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    id_order             BIGINT   NOT NULL,
    id_dish              BIGINT   NOT NULL,
    amount               INTEGER,
    comment              VARCHAR(255),

    CONSTRAINT pk_order_line        PRIMARY KEY (id),
    CONSTRAINT fk_order_line_order  FOREIGN KEY (id_order)
                                        REFERENCES orders (id)
                                        ON DELETE CASCADE,
    CONSTRAINT fk_order_line_dish   FOREIGN KEY (id_dish)
                                        REFERENCES dish (id)
                                        ON DELETE RESTRICT,

    -- BR-008: quantity must be at least 1 portion
    CONSTRAINT chk_order_line_amount CHECK (amount IS NULL OR amount >= 1)
);

COMMENT ON TABLE  order_line         IS 'One line in an order: which dish, how many, optional customer note';
COMMENT ON COLUMN order_line.amount  IS 'Number of portions; must be ≥ 1 (BR-008)';
COMMENT ON COLUMN order_line.comment IS 'Free-text customer note, e.g. "please not too spicy"';

CREATE INDEX idx_order_line_order ON order_line(id_order);
CREATE INDEX idx_order_line_dish  ON order_line(id_dish);

-- ============================================================
-- TABLE: order_dish_extra_ingredient  [Junction: OrderLine ↔ Ingredient M:N]
-- Description: Extra ingredients selected for a specific order line
-- Domain: Order Management
-- ============================================================
CREATE TABLE order_dish_extra_ingredient (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER,
    id_order_line        BIGINT  NOT NULL,
    id_ingredient        BIGINT  NOT NULL,

    CONSTRAINT pk_order_dish_extra             PRIMARY KEY (id),
    CONSTRAINT uq_order_dish_extra             UNIQUE (id_order_line, id_ingredient),
    CONSTRAINT fk_order_dish_extra_order_line  FOREIGN KEY (id_order_line)
                                                   REFERENCES order_line (id)
                                                   ON DELETE CASCADE,
    CONSTRAINT fk_order_dish_extra_ingredient  FOREIGN KEY (id_ingredient)
                                                   REFERENCES ingredient (id)
                                                   ON DELETE RESTRICT
);

COMMENT ON TABLE order_dish_extra_ingredient IS 'Extra ingredients chosen by the customer for a specific order line; many-to-many join';

CREATE INDEX idx_order_dish_extra_line ON order_dish_extra_ingredient(id_order_line);
CREATE INDEX idx_order_dish_extra_ingr ON order_dish_extra_ingredient(id_ingredient);

-- ============================================================
-- TABLE: binary_object
-- Description: Generic BLOB store (devon4j BinaryObjectService)
-- Domain: Infrastructure
-- ============================================================
CREATE TABLE binary_object (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER NOT NULL DEFAULT 0,
    content              BYTEA,
    filesize             BIGINT  NOT NULL,
    mime_type            VARCHAR(255),

    CONSTRAINT pk_binary_object    PRIMARY KEY (id),
    CONSTRAINT chk_binary_filesize CHECK (filesize >= 0)
);

COMMENT ON TABLE  binary_object          IS 'General-purpose binary object store used by the devon4j BinaryObjectService';
COMMENT ON COLUMN binary_object.filesize IS 'File size in bytes; ≥ 0';

-- ============================================================
-- TABLE: rev_info
-- Description: Hibernate Envers audit trail – one row per transaction
-- Domain: Infrastructure
-- ============================================================
CREATE TABLE rev_info (
    id          BIGINT  GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    "timestamp" BIGINT  NOT NULL,
    user_login  VARCHAR(255),

    CONSTRAINT pk_rev_info PRIMARY KEY (id)
);

COMMENT ON TABLE  rev_info             IS 'Hibernate Envers revision log; one row per audited database transaction';
COMMENT ON COLUMN rev_info."timestamp" IS 'Unix epoch milliseconds of the audited commit';
COMMENT ON COLUMN rev_info.user_login  IS 'Spring Security principal username who performed the change';

CREATE INDEX idx_rev_info_timestamp ON rev_info("timestamp");
CREATE INDEX idx_rev_info_user      ON rev_info(user_login);

-- ============================================================
-- TABLE: date_info
-- Description: Historical weather/calendar data for ML prediction
-- Domain: Analytics / Prediction
-- ============================================================
CREATE TABLE date_info (
    "date"      DATE             NOT NULL,
    temperature DOUBLE PRECISION,
    designation VARCHAR(255),

    CONSTRAINT pk_date_info PRIMARY KEY ("date")
);

COMMENT ON TABLE  date_info             IS 'Daily weather + calendar data; joined with orders for demand-prediction ML pipeline';
COMMENT ON COLUMN date_info."date"      IS 'Calendar date (primary key)';
COMMENT ON COLUMN date_info.temperature IS 'Average temperature (°C) on this day';
COMMENT ON COLUMN date_info.designation IS 'Special day label (Holiday, Festival, Workday, Weekend, ...)';

-- ============================================================
-- TABLE: prediction_all_forecast
-- Description: ML model output – per-dish demand forecasts
-- Domain: Analytics / Prediction
-- ============================================================
CREATE TABLE prediction_all_forecast (
    id                   BIGINT           GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER          NOT NULL DEFAULT 0,
    id_dish              BIGINT           NOT NULL,
    dish_name            VARCHAR(255),
    "timestamp"          INTEGER,
    forecast             DOUBLE PRECISION,

    CONSTRAINT pk_prediction_all_forecast PRIMARY KEY (id),
    CONSTRAINT fk_paf_dish FOREIGN KEY (id_dish)
                               REFERENCES dish (id)
                               ON DELETE CASCADE
);

COMMENT ON TABLE  prediction_all_forecast             IS 'Forecast demand per dish per timestamp; output of ML prediction service';
COMMENT ON COLUMN prediction_all_forecast."timestamp" IS 'Unix epoch seconds of forecast date';
COMMENT ON COLUMN prediction_all_forecast.forecast    IS 'Predicted portions for id_dish at this timestamp';

CREATE INDEX idx_paf_dish      ON prediction_all_forecast(id_dish);
CREATE INDEX idx_paf_timestamp ON prediction_all_forecast("timestamp");

-- ============================================================
-- TABLE: prediction_all_models
-- Description: Serialised ML model parameters (key-value store)
-- Domain: Analytics / Prediction
-- ============================================================
CREATE TABLE prediction_all_models (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
    modification_counter INTEGER  NOT NULL DEFAULT 0,
    id_dish              BIGINT   NOT NULL,
    "key"                VARCHAR(100),
    "value"              VARCHAR(5000),

    CONSTRAINT pk_prediction_all_models PRIMARY KEY (id),
    CONSTRAINT fk_pam_dish FOREIGN KEY (id_dish)
                               REFERENCES dish (id)
                               ON DELETE CASCADE
);

COMMENT ON TABLE  prediction_all_models IS 'Key-value store for ML model parameters per dish (e.g. ARIMA coefficients, R² score, model type)';

CREATE INDEX idx_pam_dish ON prediction_all_models(id_dish);
CREATE INDEX idx_pam_key  ON prediction_all_models("key");

-- ============================================================
-- TABLE: prediction_forecast_data
-- Description: Feature input data for ML demand forecasting
-- Domain: Analytics / Prediction
-- ============================================================
CREATE TABLE prediction_forecast_data (
    "timestamp"  INTEGER          NOT NULL,
    temperature  DOUBLE PRECISION,
    holiday      INTEGER,

    CONSTRAINT pk_prediction_forecast_data PRIMARY KEY ("timestamp"),
    CONSTRAINT chk_pfd_holiday CHECK (holiday IN (0, 1))
);

COMMENT ON TABLE  prediction_forecast_data             IS 'Feature dataset for ML demand forecasting: date + weather + holiday indicator';
COMMENT ON COLUMN prediction_forecast_data."timestamp" IS 'Unix epoch seconds (primary key)';
COMMENT ON COLUMN prediction_forecast_data.holiday     IS '1 = public holiday, 0 = normal workday';

-- ============================================================
-- TABLE: addresses
-- Description: User addresses for geo-clustering analytics
-- Domain: Analytics / Clustering
-- ============================================================
CREATE TABLE addresses (
    id_user     BIGINT       NOT NULL,
    street      VARCHAR(255),
    housenumber VARCHAR(255),
    plz         VARCHAR(255),
    city        VARCHAR(255),
    country     VARCHAR(255),
    geocode     VARCHAR(5000),

    CONSTRAINT pk_addresses      PRIMARY KEY (id_user),
    CONSTRAINT fk_addresses_user FOREIGN KEY (id_user)
                                     REFERENCES "user" (id)
                                     ON DELETE CASCADE
);

COMMENT ON TABLE  addresses         IS 'One delivery/geo address per user; used by the clustering analytics (GeoBooking view)';
COMMENT ON COLUMN addresses.plz     IS 'Postal code / ZIP code';
COMMENT ON COLUMN addresses.geocode IS 'Serialised geocoding result (lat/lng pair or GeoJSON string) for heatmap rendering';

CREATE INDEX idx_addresses_city    ON addresses(city);
CREATE INDEX idx_addresses_country ON addresses(country);

-- ============================================================
-- ANALYTICAL VIEWS
-- ============================================================

-- View: daily_ordered_dishes
-- Purpose: Aggregate dish demand per calendar day
CREATE OR REPLACE VIEW daily_ordered_dishes AS
SELECT
    ol.id_dish                  AS id_dish,
    DATE(b.booking_date)        AS booking_date,
    SUM(ol.amount)::INTEGER     AS amount
FROM order_line   ol
JOIN orders       o  ON ol.id_order  = o.id
JOIN booking      b  ON o.id_booking = b.id
GROUP BY ol.id_dish, DATE(b.booking_date)
ORDER BY booking_date, id_dish;

COMMENT ON VIEW daily_ordered_dishes IS 'Daily dish demand aggregation; join with date_info for temperature enrichment';

-- View: monthly_ordered_dishes
-- Purpose: Monthly demand with avg temperature (for seasonal ML features)
CREATE OR REPLACE VIEW monthly_ordered_dishes AS
SELECT
    ol.id_dish                                            AS id_dish,
    DATE_TRUNC('month', b.booking_date)::DATE             AS booking_date,
    ROUND(AVG(di.temperature)::NUMERIC, 1)::DOUBLE PRECISION AS temperature,
    SUM(ol.amount)::INTEGER                               AS amount
FROM order_line   ol
JOIN orders       o  ON ol.id_order  = o.id
JOIN booking      b  ON o.id_booking = b.id
JOIN date_info    di
    ON TO_CHAR(di."date", 'YYYY-MM') = TO_CHAR(b.booking_date AT TIME ZONE 'UTC', 'YYYY-MM')
GROUP BY ol.id_dish, DATE_TRUNC('month', b.booking_date)
ORDER BY booking_date, id_dish;

COMMENT ON VIEW monthly_ordered_dishes IS 'Monthly dish demand with average temperature; used by monthly ML forecasting models';

-- View: ordered_dishes_per_day
-- Purpose: Enriched daily report with dish + weather metadata (prediction service entity)
CREATE OR REPLACE VIEW ordered_dishes_per_day AS
SELECT
    (TO_CHAR(dod.booking_date, 'YYYYMMDD') || dod.id_dish::TEXT)::BIGINT AS id,
    d.modification_counter,
    di.temperature,
    di.designation,
    dod.id_dish,
    dod.booking_date,
    dod.amount
FROM daily_ordered_dishes dod
JOIN dish      d  ON dod.id_dish   = d.id
JOIN date_info di ON di."date"     = dod.booking_date;

COMMENT ON VIEW ordered_dishes_per_day IS 'Full daily order report with dish metadata and weather data; mapped by OrderedDishesPerDayEntity JPA view entity';

-- View: ordered_dishes_per_month
-- Purpose: Enriched monthly report with dish metadata (prediction service entity)
CREATE OR REPLACE VIEW ordered_dishes_per_month AS
SELECT
    (TO_CHAR(mod2.booking_date, 'YYYYMMDD') || mod2.id_dish::TEXT)::BIGINT AS id,
    d.modification_counter,
    mod2.id_dish,
    mod2.booking_date,
    mod2.temperature,
    mod2.amount
FROM monthly_ordered_dishes mod2
JOIN dish d ON mod2.id_dish = d.id;

COMMENT ON VIEW ordered_dishes_per_month IS 'Full monthly order report with dish metadata; mapped by OrderedDishesPerMonthEntity JPA view entity';

-- View: geo_booking
-- Purpose: Spatial join of orders → users → addresses for clustering/heatmap
CREATE OR REPLACE VIEW geo_booking AS
SELECT
    ol.id_dish,
    d.name      AS dish_name,
    b.booking_date,
    a.geocode,
    ol.amount
FROM booking    b
JOIN "user"     u  ON u.id         = b.id_user
JOIN addresses  a  ON u.id         = a.id_user
JOIN orders     o  ON o.id_booking = b.id
JOIN order_line ol ON o.id         = ol.id_order
JOIN dish       d  ON d.id         = ol.id_dish;

COMMENT ON VIEW geo_booking IS 'Spatial analytics view: orders + user geocodes; used by clustering / demand heatmap features';

-- ============================================================
-- TRIGGER: Auto-increment modification_counter on UPDATE
-- Emulates JPA @Version optimistic-locking (BR-012)
-- ============================================================
CREATE OR REPLACE FUNCTION trg_increment_modification_counter()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modification_counter = OLD.modification_counter + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION trg_increment_modification_counter() IS
    'Auto-increments modification_counter on every UPDATE row; mirrors JPA @Version optimistic-locking (BR-012)';

-- Apply modification_counter trigger to all versioned tables
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'user_role',
        'image',
        'category',
        'ingredient',
        '"user"',
        'dish',
        'dish_category',
        'dish_ingredient',
        'user_favourite',
        'restaurant_table',
        'booking',
        'invited_guest',
        'orders',
        'order_line',
        'order_dish_extra_ingredient',
        'binary_object',
        'prediction_all_forecast',
        'prediction_all_models'
    ] LOOP
        EXECUTE format(
            $fmt$
            CREATE TRIGGER trg_%s_mod_counter
            BEFORE UPDATE ON %s
            FOR EACH ROW
            EXECUTE FUNCTION trg_increment_modification_counter()
            $fmt$,
            replace(replace(tbl, '"', ''), '.', '_'),
            tbl
        );
    END LOOP;
END;
$$;

-- ============================================================
-- SEED DATA  –  Reference / Master Data
-- ============================================================

-- ── User Roles ──
INSERT INTO user_role (id, modification_counter, name, active) VALUES
    (0, 1, 'Customer', TRUE),
    (1, 1, 'Waiter',   TRUE),
    (2, 1, 'Manager',  TRUE);

-- ── Users (passwords are bcrypt-hashed, Spring Security {bcrypt} prefix) ──
INSERT INTO "user" (id, modification_counter, username, password, two_factor_status, email, id_role) VALUES
    (0, 1, 'user0',   '{bcrypt}$2a$10$qPM1WjcRKAffHxWXYEfPJOh2vGPlT/Fdv.hJX/LaZjzg/Wtj2csqO', FALSE, 'user0@mail.com',   0),
    (1, 1, 'waiter',  '{bcrypt}$2a$10$1CAKyUHbX6RJqT5cUP6/aOMTIlYYvGIO/a3Dt/erbYKKgmbgJMGsG', FALSE, 'waiter@mail.com',  1),
    (2, 1, 'manager', '{bcrypt}$2a$10$IsTlZemkiPKE2gjtnSMlJOX5.uitNHXNRpLYyvyxNbHEhjpY.XdTq', FALSE, 'manager@mail.com', 2);

-- ── Restaurant Tables (seating: 4 / 6 / 8) ──
INSERT INTO restaurant_table (id, modification_counter, seats_number) VALUES
    (0, 1, 4), (1, 1, 4), (2, 1, 4), (3, 1, 4),  -- 4-seat tables (IDs 0-3)
    (4, 1, 6), (5, 1, 6), (6, 1, 6),              -- 6-seat tables (IDs 4-6)
    (7, 1, 8), (8, 1, 8);                         -- 8-seat tables (IDs 7-8)

-- ── Dish Categories ──
INSERT INTO category (id, modification_counter, name, description, show_order) VALUES
    (0,  1, 'Thai',        'Traditional Thai dishes',                  1),
    (1,  1, 'Vegetarian',  'Dishes without meat or fish',              2),
    (2,  1, 'Vegan',       'Plant-based, no animal products',          3),
    (3,  1, 'Noodle',      'Noodle-based dishes',                      4),
    (4,  1, 'Rice',        'Rice-based dishes',                        5),
    (5,  1, 'Curry',       'Curried dishes with coconut milk or broth',6),
    (6,  1, 'Starter',     'Appetisers and starters',                  7),
    (7,  1, 'Main',        'Main course dishes',                       8),
    (8,  1, 'Dessert',     'Sweet desserts and confections',           9),
    (9,  1, 'Beverage',    'Hot and cold drinks',                     10);

-- ── Sample Bookings (with relative dates for environment portability) ──
-- Note: actual booking data uses DATEADD relative to CURRENT_TIMESTAMP.
-- For PostgreSQL, use interval arithmetic:

INSERT INTO booking (id, modification_counter, id_user, name, booking_token, comment,
                     email, booking_date, expiration_date, creation_date,
                     canceled, booking_type, id_table, assistants)
VALUES
    -- Common (CSR) booking with existing order
    (0, 1, 0, 'user0', 'CB_20170509_123502555zzzzzzzzzzzzzzzzz',
     'Booking Type CSR', 'user0@mail.com',
     CURRENT_TIMESTAMP + INTERVAL '5 days',
     CURRENT_TIMESTAMP + INTERVAL '5 days' - INTERVAL '1 hour',
     CURRENT_TIMESTAMP, FALSE, 0, 0, 3),

    -- Guest-invite (GSR) booking
    (1, 1, 0, 'user1', 'CB_20170510_123502575zzzzzzzzzzzzzzzzz',
     'Booking Type GSR', 'user1@mail.com',
     CURRENT_TIMESTAMP + INTERVAL '5 days',
     CURRENT_TIMESTAMP + INTERVAL '5 days' - INTERVAL '1 hour',
     CURRENT_TIMESTAMP, FALSE, 1, 1, NULL),

    -- Common booking without orders yet
    (2, 1, 0, 'user2', 'CB_20170510_123502595zzzzzzzzzzzzzzzzz',
     'Booking Type GSR', 'user2@mail.com',
     CURRENT_TIMESTAMP + INTERVAL '5 days',
     CURRENT_TIMESTAMP + INTERVAL '5 days' - INTERVAL '1 hour',
     CURRENT_TIMESTAMP, FALSE, 0, 2, 5),

    -- Host booking for group (host1)
    (3, 1, 0, 'host1', 'CB_20170510_123502655zzzzzzzzzzzzzzzzz',
     'Booking Type GSR', 'host1@mail.com',
     CURRENT_TIMESTAMP + INTERVAL '5 days',
     CURRENT_TIMESTAMP + INTERVAL '5 days' - INTERVAL '1 hour',
     CURRENT_TIMESTAMP, FALSE, 1, 3, NULL),

    -- Second host booking for group (host1, table 3)
    (4, 1, 0, 'host1', 'CB_20170510_123503600zzzzzzzzzzzzzzzzz',
     'Booking Type GSR', 'host1@mail.com',
     CURRENT_TIMESTAMP + INTERVAL '5 days',
     CURRENT_TIMESTAMP + INTERVAL '5 days' - INTERVAL '1 hour',
     CURRENT_TIMESTAMP, FALSE, 1, 3, NULL);

-- ── Invited Guests for booking id=3 ──
INSERT INTO invited_guest (id, modification_counter, id_booking, guest_token, email, accepted, modification_date)
VALUES
    (0, 1, 3, 'GB_20170510_02350266501zzzzzzzzzzzzzzzz', 'guest0@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (1, 1, 3, 'GB_20170510_12350266501zzzzzzzzzzzzzzzz', 'guest1@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (2, 1, 3, 'GB_20170510_22350266501zzzzzzzzzzzzzzzz', 'guest2@mail.com', FALSE, CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (3, 1, 3, 'GB_20170510_32350266501zzzzzzzzzzzzzzzz', 'guest3@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (4, 1, 3, 'GB_20170510_42350266501zzzzzzzzzzzzzzzz', 'guest4@mail.com', FALSE, CURRENT_TIMESTAMP + INTERVAL '5 days');

-- ── Invited Guests for booking id=4 ──
INSERT INTO invited_guest (id, modification_counter, id_booking, guest_token, email, accepted, modification_date)
VALUES
    (5, 1, 4, 'GB_20170510_52350266501zzzzzzzzzzzzzzzz', 'guest5@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (6, 1, 4, 'GB_20170510_62350266501zzzzzzzzzzzzzzzz', 'guest6@mail.com', FALSE, CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (7, 1, 4, 'GB_20170510_72350266501zzzzzzzzzzzzzzzz', 'guest7@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (8, 1, 4, 'GB_20170510_82350266501zzzzzzzzzzzzzzzz', 'guest0@mail.com', TRUE,  CURRENT_TIMESTAMP + INTERVAL '5 days'),
    (9, 1, 4, 'GB_20170510_92350266501zzzzzzzzzzzzzzzz', 'guest1@mail.com', FALSE, CURRENT_TIMESTAMP + INTERVAL '5 days');

-- ── Orders ──
-- Seeded BEFORE updating booking.id_order (deferred FK)
INSERT INTO orders (id, modification_counter, id_booking, id_invited_guest, id_host) VALUES
    (0, 1, 0, NULL, 0),   -- host order for booking 0
    (1, 1, 3, 0,    NULL), -- guest order: booking 3, guest 0
    (2, 1, 3, 1,    NULL), -- guest order: booking 3, guest 1
    (3, 1, 3, 2,    NULL), -- guest order: booking 3, guest 2
    (4, 1, 3, 3,    NULL), -- guest order: booking 3, guest 3
    (5, 1, 3, 4,    NULL), -- guest order: booking 3, guest 4
    (6, 1, 4, 8,    NULL), -- guest order: booking 4, guest 8
    (7, 1, 4, 9,    NULL); -- guest order: booking 4, guest 9

-- Update booking.id_order (circular FK, now safe because orders exist)
UPDATE booking SET id_order = 0 WHERE id = 0;
UPDATE booking SET id_order = 1 WHERE id = 3;

-- ── Order Lines ──
INSERT INTO order_line (id, modification_counter, id_dish, amount, comment, id_order) VALUES
    (0,  1, 0, 2, 'please not too spicy', 0),
    (1,  1, 4, 1, NULL,                   0),
    (2,  1, 2, 1, NULL,                   0),
    (3,  1, 4, 2, NULL,                   1),
    (4,  1, 2, 1, NULL,                   1),
    (5,  1, 3, 1, NULL,                   1),
    (6,  1, 2, 1, NULL,                   2),
    (7,  1, 5, 1, NULL,                   3),
    (8,  1, 5, 1, NULL,                   4),
    (9,  1, 3, 1, NULL,                   5),
    (10, 1, 5, 2, NULL,                   6),
    (11, 1, 3, 1, NULL,                   7);

-- ── Extra Ingredients on Order Lines ──
INSERT INTO order_dish_extra_ingredient (id, modification_counter, id_order_line, id_ingredient) VALUES
    (0, 1, 0, 1),
    (1, 1, 1, 1),
    (2, 1, 2, 0),
    (3, 1, 2, 1),
    (4, 1, 4, 0),
    (5, 1, 5, 0);

-- ============================================================
-- END OF SCHEMA  –  My Thai Star PostgreSQL DDL
-- ============================================================
